### ISSUE TITLE
Missing "&" in ToC title

### ISSUE THREAD

**Issue by abrudz** [Dyalog/documentation#33]
https://dyalog.github.io/documentation/20.0/interface-guide/dde/restrictions-limitations/ has the title "Restrictions & Limitations" but the ToC just says "Restrictions Limitations":
![image](https://github.com/user-attachments/assets/ce2ce0d0-42c4-4deb-bdf0-ea5ff6a336a2)

**Comment by xpqz** [comment]
Fixed in 0f0558faae8e77dba8c7b3a727ec61c4fa2611c5
